language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - if [[ $TRAVIS_PHP_VERSION = 5.6 ]]; then COVERAGE_NEEDED=true; else COVERAGE_NEEDED=false; fi
  - >
    if [[ $COVERAGE_NEEDED = true ]]; then
        PHPUNIT_FLAGS="--coverage-text --coverage-clover=coverage.clover";
    else
        PHPUNIT_FLAGS="";
        phpenv config-rm xdebug.ini || true;
    fi
  - composer install --no-interaction

script:
  - bin/phpunit -c app/phpunit.xml.dist $PHPUNIT_FLAGS

after_script:
  - >
    if [[ $COVERAGE_NEEDED = true ]]; then
        wget https://scrutinizer-ci.com/ocular.phar;
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
    fi
